#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=00:01:00
#PBS -N myjob0
#PBS -o myjob.out
#PBS -e myjob.err
#PBS -q workq
#PBS -A loni_droz50ksv
#PBS -m e
#PBS -M droz@latech.edu

mpirun -machinefile $PBS_NODEFILE -np 20 ./a.out
